version: '3.8'

networks:
  portal_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
    bot:
        build:
            context: ./bot
            dockerfile: Dockerfile
        networks:
            portal_network:
                # this IP must be private and NOT EXPOSED via any proxy to the
                # public
                ipv4_address: ${BOT_PRIVATE_IP}
        env_file:
            - ./.env
        volumes:
            - ./server_config.ini:/app/server_config.ini
        tty: true

    portal:
        build:
            context: ./portal
            dockerfile: Dockerfile
        networks:
            portal_network:
                ipv4_address: ${PORTAL_PRIVATE_IP}
        env_file:
            - ./.env
        volumes:
            - ./server_config.ini:/app/server_config.ini
        tty: true
