version: '3.8'

services:
    bot:
        build:
            context: ./bot
            dockerfile: Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./server_config.ini:/app/server_config.ini
        tty: true

    portal:
        build:
            context: ./portal
            dockerfile: Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./server_config.ini:/app/server_config.ini
        tty: true
